name: remote ssh command
#on: [push]
on:
  workflow_dispatch:
  push:
    branches:
      - stage
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: "22"
        script: cd /srv/www/back-getxml.stage && git checkout stage && git pull origin stage && docker rm imobiliarianorte-getxml.vm-getxml-stage -f && docker image rm imobiliaria-norte/getxml-stage && docker-compose up -f stage.yml --detach
